#!/bin/dash


branches=".pushy/branches"

if [ $# -eq 0 ]; then
	if ! ls .pushy/rep/* >/dev/null 2>&1; then
		echo "pushy-branch: error: this command can not be run until after the first commit"
		exit 1
	fi
	if ls "$branches"/*/ >/dev/null 2>&1; then
		for dir in "$branches"/*/; do
			dirname=$(basename "$dir")
    			echo "${dirname%/}" 
		done
	fi
elif [ $# -eq 1 ]; then
	    if [ "$1" = "-d" ]; then
		    echo "Error: branch name is required for deletion." >&2
		    exit 1
	    elif echo "$1" | grep -q "^-" && [ "$1" != "-d" ];then
		    echo "usage: pushy-branch [-d] <branch> " >&2 
		    exit 1
	    else
		    branch_name="$1"
        	    if [ -d "$branches/$branch_name" ]; then
			    echo "pushy-branch: error: branch '$branch_name' already exists" >&2
			    exit 1
        	    else
			    mkdir "$branches/$branch_name"
			    cp -r .pushy/rep "$branches/$branch_name/"
		    fi
	    fi
elif [ $# -eq 2 ]; then

	if [ "$1" = "-d" ]; then

		branch_name="$2"
		if [ -d "$branches/$branch_name" ]; then
			if [ "$branch_name" = "master" ]; then
				echo "pushy-branch: error: can not delete branch 'master': default branch"
				exit 1
			fi
		        rm -r "${branches:?}/${branch_name:?}"
			echo "Deleted branch '$branch_name'"
		else
			echo "pushy-branch: error: branch '$branch_name' doesn't exist" >&2
			exit 1
		fi
	else

		echo "usage: pushy-branch [-d] <branch> " >&2
		exit 1
	fi
else
	echo "usage: pushy-branch [-d] <branch>" >&2
	exit 1
fi
exit 0 
